-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 16:06:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lis` DEFAULT CHARACTER SET utf8 ;
USE `lis` ;

-- -----------------------------------------------------
-- Table `lis`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `tax` INT NOT NULL,
  `patient_id_prefix` VARCHAR(10) NOT NULL,
  `patient_id_count_start` INT NOT NULL,
  `sample_label_prefix` VARCHAR(45) NOT NULL,
  `sample_label_count_start` INT NOT NULL,
  `s3_folder_name` VARCHAR(45) NOT NULL,
  `register_date` VARCHAR(45) NOT NULL,
  `test_limit` INT NOT NULL,
  `user_limit` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`admin` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  `register_date` VARCHAR(45) NULL,
  `organization_id` INT NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_admin_organization1_idx` (`organization_id` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  CONSTRAINT `fk_admin_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `lis`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `test_id` VARCHAR(45) NULL,
  `name` TEXT NOT NULL,
  `price` INT NULL,
  `tat` INT NULL,
  `description` TEXT NULL,
  `register_date` VARCHAR(45) NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  INDEX `fk_test_admin1_idx` (`admin_username` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `testId_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_test_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `address` TEXT NULL,
  `employee_id` VARCHAR(45) NULL,
  `register_date` VARCHAR(45) NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `user_role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_admin1_idx` (`admin_username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_user_user_role1_idx` (`user_role_id` ASC),
  CONSTRAINT `fk_user_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `lis`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`bill_format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`bill_format` (
  `id` INT(11) GENERATED ALWAYS AS () VIRTUAL,
  `due_days` INT(11) NOT NULL,
  `tax` INT(11) NULL DEFAULT NULL,
  `tax_type` VARCHAR(45) NULL,
  `heading` TEXT NULL DEFAULT NULL,
  `sub_heading` TEXT NULL DEFAULT NULL,
  `number` VARCHAR(15) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(18) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `invoice_number_prefix` VARCHAR(15) NULL DEFAULT NULL,
  `term1` TEXT NULL DEFAULT NULL,
  `term2` TEXT NULL DEFAULT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bill_format_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_bill_format_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`patient` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `name_prefix` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `blood_group` VARCHAR(5) NOT NULL,
  `date_of_birth` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_patient_admin1_idx` (`admin_username` ASC),
  INDEX `fk_patient_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_patient_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` VARCHAR(45) NOT NULL,
  `patient_id` INT(11) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_visit_patient1_idx` (`patient_id` ASC),
  INDEX `fk_visit_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_visit_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `lis`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`patient_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`patient_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT(11) NOT NULL,
  `status` VARCHAR(45) NULL,
  `count` INT NULL,
  `select_date` VARCHAR(45) NULL,
  `visit_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  INDEX `fk_patient_test_patient1_idx` (`patient_id` ASC),
  INDEX `fk_patient_test_visit1_idx` (`visit_id` ASC),
  INDEX `fk_patient_test_test1_idx` (`test_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_patient_test_user1_idx` (`user_id` ASC),
  INDEX `fk_patient_test_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_patient_test_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `lis`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_test_visit1`
    FOREIGN KEY (`visit_id`)
    REFERENCES `lis`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `lis`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_test_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_test_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`patient_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`patient_document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `size` INT NULL,
  `last_modified_date` VARCHAR(45) NULL,
  `patient_id` INT(11) NOT NULL,
  `user_id` INT NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  INDEX `fk_patient_document_patient1_idx` (`patient_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_patient_document_user1_idx` (`user_id` ASC),
  INDEX `fk_patient_document_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_patient_document_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `lis`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_document_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_document_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`invoice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `balance` INT(11) NOT NULL,
  `paid` INT(11) NOT NULL,
  `total` INT(11) NOT NULL,
  `generate_date` VARCHAR(45) NOT NULL,
  `update_date` VARCHAR(45) NULL,
  `patient_id` INT(11) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `visit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoiceId_UNIQUE` (`id` ASC),
  INDEX `fk_invoice_patient1_idx` (`patient_id` ASC),
  INDEX `fk_invoice_admin1_idx` (`admin_username` ASC),
  INDEX `fk_invoice_user1_idx` (`user_id` ASC),
  INDEX `fk_invoice_visit1_idx` (`visit_id` ASC),
  CONSTRAINT `fk_invoice_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `lis`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_visit1`
    FOREIGN KEY (`visit_id`)
    REFERENCES `lis`.`visit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`user_login_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`user_login_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NOT NULL,
  `ip` VARCHAR(20) NOT NULL,
  `date` VARCHAR(12) NOT NULL,
  `time` VARCHAR(12) NOT NULL,
  `status` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`sample_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`sample_label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label_id` INT NULL,
  `timestamp` VARCHAR(45) NULL,
  `patient_id` INT(11) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sample_label_patient1_idx` (`patient_id` ASC),
  INDEX `fk_sample_label_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_sample_label_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `lis`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sample_label_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`message_body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`message_body` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(15) NOT NULL,
  `sender_id` VARCHAR(6) NOT NULL,
  `message` TEXT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_message_body_admin1_idx` (`admin_username` ASC),
  CONSTRAINT `fk_message_body_admin1`
    FOREIGN KEY (`admin_username`)
    REFERENCES `lis`.`admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`user_otp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`user_otp` (
  `number` VARCHAR(45) NOT NULL,
  `otp` INT NOT NULL,
  `count` INT NOT NULL,
  `timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lis`.`admin_otp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lis`.`admin_otp` (
  `number` VARCHAR(45) NOT NULL,
  `otp` INT NOT NULL,
  `count` INT NOT NULL,
  `timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
